discord:
  botToken: MTExNjgzODA4NTgwODg5ODE5OQ.GQogSU.N3dzLgY8ciqbWGT4SDOXk6DdmtuTA7q4S6WNoY
  serverId: "770057600867237898"
  channels:
    {
      welcomeChanelId: "1088581487470850140",
      adminChanelId: "1060368458816172112",
      whitelistChanelId: "1060368458816172112",
      botLogChannelId: "1060368458816172112",
      javaLogChannelId: "1060368458816172112",
    }
  roles:
    {
      discordAdminRoleId: "1090853358786588795",
      moderatorRoleId: "1090853850489036811",
      devRoleId: "1090854262751371344",
      helperRoleId: "1090854380745535538",
    }
database:
  {
    type: mysql,
    host: localhost,
    port: "3306",
    name: minecraft,
    user: minecraft,
    password: h6u9effkcj735vcypxxj8durh9rjzkjz,
    defaultTable: wje_users,
    maxConnection: "15",
    maxIdleConnection: "5",
  }
minecraft:
  {
    portJava: "25565",
    portBedrock: "19132",
    javaIp: tempcity.click,
    bedrockIp: bedrock.tempcity.click,
  }
features: { maxHoursFor2FA: "48", showAllWorldsMeteo: "false", defaultLang: EN }
misc:
  {
    confirmLinkCmdName: wje-link,
    minecraftInfosLink: "https://www.fiverr.com/rvdprojects",
    serverContactEmail: webdevteam@rvdprojects.com,
  }
