name: WhitelistJe
version: '${project.version}'
main: main.WhitelistJe
api-version: 1.15
author: Izocel
commands:
   wlink:
      description: Used to authenticate your Discord and Minecraft accounts.
      usage: /<wlink-command>
